export type CardNoId = {
  pack_code: string;
  pack_name: string;
  type_code: string;
  type_name: string;
  sphere_code: string;
  sphere_name: string;
  position: number;
  code: string;
  name: string;
  traits: string;
  text: string;
  flavor: string;
  is_unique: boolean;
  quantity: number;
  deck_limit: number;
  illustrator: string;
  octgnid: string;
  has_errata: boolean;
  url: string;
  imagesrc: string;
  cost?: string;
  willpower?: number;
  attack?: number;
  defense?: number;
  health?: number;
  threat?: number;
};

export type Card = CardNoId & { id: number };
